# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Choice.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(330, 100, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.fullscreen = QtWidgets.QCheckBox(Form)
        self.fullscreen.setGeometry(QtCore.QRect(240, 440, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fullscreen.setFont(font)
        self.fullscreen.setChecked(False)
        self.fullscreen.setObjectName("fullscreen")
        self.historique = QtWidgets.QCheckBox(Form)
        self.historique.setGeometry(QtCore.QRect(240, 470, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.historique.setFont(font)
        self.historique.setChecked(False)
        self.historique.setObjectName("historique")
        self.taille = QtWidgets.QLCDNumber(Form)
        self.taille.setGeometry(QtCore.QRect(580, 430, 64, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.taille.setFont(font)
        self.taille.setFocusPolicy(QtCore.Qt.NoFocus)
        self.taille.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.taille.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.taille.setFrameShape(QtWidgets.QFrame.Panel)
        self.taille.setFrameShadow(QtWidgets.QFrame.Plain)
        self.taille.setSmallDecimalPoint(False)
        self.taille.setProperty("value", 40.0)
        self.taille.setObjectName("taille")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(450, 470, 331, 51))
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.horizontalSlider.setMaximum(300)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 40)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(25)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(10, 550, 791, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.show_grpah = QtWidgets.QCheckBox(Form)
        self.show_grpah.setGeometry(QtCore.QRect(60, 500, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.show_grpah.setFont(font)
        self.show_grpah.setChecked(False)
        self.show_grpah.setObjectName("show_grpah")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 272, 161, 71))
        self.pushButton.setObjectName("pushButton")
        self.affichage = QtWidgets.QCheckBox(Form)
        self.affichage.setGeometry(QtCore.QRect(60, 380, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.affichage.setFont(font)
        self.affichage.setChecked(True)
        self.affichage.setObjectName("affichage")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 270, 161, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(310, 40, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.family_Agression = QtWidgets.QCheckBox(Form)
        self.family_Agression.setGeometry(QtCore.QRect(240, 410, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.family_Agression.setFont(font)
        self.family_Agression.setChecked(False)
        self.family_Agression.setObjectName("family_Agression")
        self.Day_Box = QtWidgets.QSpinBox(Form)
        self.Day_Box.setGeometry(QtCore.QRect(360, 150, 101, 31))
        self.Day_Box.setMinimum(1)
        self.Day_Box.setMaximum(100000)
        self.Day_Box.setObjectName("Day_Box")
        self.show_Perception = QtWidgets.QCheckBox(Form)
        self.show_Perception.setGeometry(QtCore.QRect(60, 440, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.show_Perception.setFont(font)
        self.show_Perception.setChecked(False)
        self.show_Perception.setObjectName("show_Perception")
        self.show_Minimap = QtWidgets.QCheckBox(Form)
        self.show_Minimap.setGeometry(QtCore.QRect(60, 410, 85, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.show_Minimap.setFont(font)
        self.show_Minimap.setChecked(True)
        self.show_Minimap.setObjectName("show_Minimap")
        self.show_Bord_Case = QtWidgets.QCheckBox(Form)
        self.show_Bord_Case.setGeometry(QtCore.QRect(60, 470, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.show_Bord_Case.setFont(font)
        self.show_Bord_Case.setChecked(False)
        self.show_Bord_Case.setObjectName("show_Bord_Case")
        self.family_Reproduction = QtWidgets.QCheckBox(Form)
        self.family_Reproduction.setGeometry(QtCore.QRect(240, 380, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.family_Reproduction.setFont(font)
        self.family_Reproduction.setChecked(False)
        self.family_Reproduction.setObjectName("family_Reproduction")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(490, 380, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.normal)
        self.progressBar.valueChanged['int'].connect(Form.barMax)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Jour de départ"))
        self.fullscreen.setText(_translate("Form", "FullScreen"))
        self.historique.setText(_translate("Form", "Historique"))
        self.show_grpah.setText(_translate("Form", "Show Graph"))
        self.pushButton.setText(_translate("Form", "Normal"))
        self.affichage.setText(_translate("Form", "Affichage"))
        self.pushButton_2.setText(_translate("Form", "Game of BoB"))
        self.label.setText(_translate("Form", "BOB BAR"))
        self.family_Agression.setText(_translate("Form", "Family Aggression"))
        self.show_Perception.setText(_translate("Form", "Show Perception"))
        self.show_Minimap.setText(_translate("Form", "Minimap"))
        self.show_Bord_Case.setText(_translate("Form", "Show Bord Case"))
        self.family_Reproduction.setText(_translate("Form", "Family Reproduction"))
        self.label_3.setText(_translate("Form", "Taille"))

