# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Choice.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 252, 161, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 250, 161, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Day_Box = QtWidgets.QSpinBox(self.centralwidget)
        self.Day_Box.setGeometry(QtCore.QRect(350, 130, 101, 31))
        self.Day_Box.setMinimum(1)
        self.Day_Box.setMaximum(100000)
        self.Day_Box.setObjectName("Day_Box")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 80, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 530, 791, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.show_Minimap = QtWidgets.QCheckBox(self.centralwidget)
        self.show_Minimap.setGeometry(QtCore.QRect(50, 390, 85, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.show_Minimap.setFont(font)
        self.show_Minimap.setChecked(True)
        self.show_Minimap.setObjectName("show_Minimap")
        self.affichage = QtWidgets.QCheckBox(self.centralwidget)
        self.affichage.setGeometry(QtCore.QRect(50, 360, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.affichage.setFont(font)
        self.affichage.setChecked(True)
        self.affichage.setObjectName("affichage")
        self.show_Perception = QtWidgets.QCheckBox(self.centralwidget)
        self.show_Perception.setGeometry(QtCore.QRect(50, 420, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.show_Perception.setFont(font)
        self.show_Perception.setChecked(False)
        self.show_Perception.setObjectName("show_Perception")
        self.show_Bord_Case = QtWidgets.QCheckBox(self.centralwidget)
        self.show_Bord_Case.setGeometry(QtCore.QRect(50, 450, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.show_Bord_Case.setFont(font)
        self.show_Bord_Case.setChecked(False)
        self.show_Bord_Case.setObjectName("show_Bord_Case")
        self.family_Reproduction = QtWidgets.QCheckBox(self.centralwidget)
        self.family_Reproduction.setGeometry(QtCore.QRect(230, 360, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.family_Reproduction.setFont(font)
        self.family_Reproduction.setChecked(False)
        self.family_Reproduction.setObjectName("family_Reproduction")
        self.family_Agression = QtWidgets.QCheckBox(self.centralwidget)
        self.family_Agression.setGeometry(QtCore.QRect(230, 390, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.family_Agression.setFont(font)
        self.family_Agression.setChecked(False)
        self.family_Agression.setObjectName("family_Agression")
        self.fullscreen = QtWidgets.QCheckBox(self.centralwidget)
        self.fullscreen.setGeometry(QtCore.QRect(230, 420, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fullscreen.setFont(font)
        self.fullscreen.setChecked(False)
        self.fullscreen.setObjectName("fullscreen")
        self.historique = QtWidgets.QCheckBox(self.centralwidget)
        self.historique.setGeometry(QtCore.QRect(230, 450, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.historique.setFont(font)
        self.historique.setChecked(False)
        self.historique.setObjectName("historique")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(440, 450, 331, 51))
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.horizontalSlider.setMaximum(300)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 40)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(25)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.taille = QtWidgets.QLCDNumber(self.centralwidget)
        self.taille.setGeometry(QtCore.QRect(570, 410, 64, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.taille.setFont(font)
        self.taille.setFocusPolicy(QtCore.Qt.NoFocus)
        self.taille.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.taille.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.taille.setFrameShape(QtWidgets.QFrame.Panel)
        self.taille.setFrameShadow(QtWidgets.QFrame.Plain)
        self.taille.setSmallDecimalPoint(False)
        self.taille.setProperty("value", 40.0)
        self.taille.setObjectName("taille")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 360, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.normal)
        self.pushButton_2.clicked.connect(MainWindow.close)
        self.progressBar.valueChanged['int'].connect(MainWindow.barMax)
        self.horizontalSlider.valueChanged['int'].connect(self.taille.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Normal"))
        self.pushButton_2.setText(_translate("MainWindow", "Game of BoB"))
        self.label.setText(_translate("MainWindow", "BOB BAR"))
        self.label_2.setText(_translate("MainWindow", "Jour de départ"))
        self.show_Minimap.setText(_translate("MainWindow", "Minimap"))
        self.affichage.setText(_translate("MainWindow", "Affichage"))
        self.show_Perception.setText(_translate("MainWindow", "Show Perception"))
        self.show_Bord_Case.setText(_translate("MainWindow", "Show Bord Case"))
        self.family_Reproduction.setText(_translate("MainWindow", "Family Reproduction"))
        self.family_Agression.setText(_translate("MainWindow", "Family Aggression"))
        self.fullscreen.setText(_translate("MainWindow", "FullScreen"))
        self.historique.setText(_translate("MainWindow", "Historique"))
        self.label_3.setText(_translate("MainWindow", "Taille"))

