# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view\Settings.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(556, 386)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.show_Biomes = QtWidgets.QCheckBox(self.tab)
        self.show_Biomes.setGeometry(QtCore.QRect(240, 200, 122, 21))
        self.show_Biomes.setObjectName("show_Biomes")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 128, 158))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.show_Bord_Case = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Bord_Case.setObjectName("show_Bord_Case")
        self.verticalLayout.addWidget(self.show_Bord_Case)
        self.show_Perception = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Perception.setObjectName("show_Perception")
        self.verticalLayout.addWidget(self.show_Perception)
        self.show_Memory = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Memory.setObjectName("show_Memory")
        self.verticalLayout.addWidget(self.show_Memory)
        self.show_Nature = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Nature.setObjectName("show_Nature")
        self.verticalLayout.addWidget(self.show_Nature)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(181, 21, 133, 77))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.show_Minimap = QtWidgets.QCheckBox(self.layoutWidget1)
        self.show_Minimap.setObjectName("show_Minimap")
        self.verticalLayout_5.addWidget(self.show_Minimap)
        self.show_Food_ProgressBar = QtWidgets.QCheckBox(self.layoutWidget1)
        self.show_Food_ProgressBar.setObjectName("show_Food_ProgressBar")
        self.verticalLayout_5.addWidget(self.show_Food_ProgressBar)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 152, 104))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 152, 104))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.animationY = QtWidgets.QRadioButton(self.groupBox)
        self.animationY.setObjectName("animationY")
        self.horizontalLayout_2.addWidget(self.animationY)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.update_rate = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.update_rate.setObjectName("update_rate")
        self.horizontalLayout_2.addWidget(self.update_rate)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.animationN = QtWidgets.QRadioButton(self.groupBox)
        self.animationN.setObjectName("animationN")
        self.horizontalLayout_2.addWidget(self.animationN)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -33, 511, 296))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter_2 = QtWidgets.QSplitter(self.scrollAreaWidgetContents_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.abcissa_tick = QtWidgets.QRadioButton(self.groupBox_3)
        self.abcissa_tick.setObjectName("abcissa_tick")
        self.horizontalLayout.addWidget(self.abcissa_tick)
        self.absyssa_days = QtWidgets.QRadioButton(self.groupBox_3)
        self.absyssa_days.setObjectName("absyssa_days")
        self.horizontalLayout.addWidget(self.absyssa_days)
        self.verticalLayout_6.addWidget(self.splitter_2)
        self.gfood = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.gfood.setObjectName("gfood")
        self.verticalLayout_6.addWidget(self.gfood)
        self.gpop = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.gpop.setObjectName("gpop")
        self.verticalLayout_6.addWidget(self.gpop)
        self.Mass_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Mass_3.setObjectName("Mass_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.Mass_3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.mass_min = QtWidgets.QCheckBox(self.Mass_3)
        self.mass_min.setObjectName("mass_min")
        self.horizontalLayout_14.addWidget(self.mass_min)
        self.mass_av = QtWidgets.QCheckBox(self.Mass_3)
        self.mass_av.setObjectName("mass_av")
        self.horizontalLayout_14.addWidget(self.mass_av)
        self.mass_max = QtWidgets.QCheckBox(self.Mass_3)
        self.mass_max.setObjectName("mass_max")
        self.horizontalLayout_14.addWidget(self.mass_max)
        self.verticalLayout_6.addWidget(self.Mass_3)
        self.velocity_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.velocity_3.setObjectName("velocity_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.velocity_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.velo_min = QtWidgets.QCheckBox(self.velocity_3)
        self.velo_min.setObjectName("velo_min")
        self.gridLayout_2.addWidget(self.velo_min, 0, 0, 1, 1)
        self.velo_av = QtWidgets.QCheckBox(self.velocity_3)
        self.velo_av.setObjectName("velo_av")
        self.gridLayout_2.addWidget(self.velo_av, 0, 1, 1, 1)
        self.velo_max = QtWidgets.QCheckBox(self.velocity_3)
        self.velo_max.setObjectName("velo_max")
        self.gridLayout_2.addWidget(self.velo_max, 0, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.velocity_3)
        self.Memory_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Memory_3.setObjectName("Memory_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.Memory_3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.memory_min = QtWidgets.QCheckBox(self.Memory_3)
        self.memory_min.setObjectName("memory_min")
        self.horizontalLayout_15.addWidget(self.memory_min)
        self.memory_av = QtWidgets.QCheckBox(self.Memory_3)
        self.memory_av.setObjectName("memory_av")
        self.horizontalLayout_15.addWidget(self.memory_av)
        self.memory_max = QtWidgets.QCheckBox(self.Memory_3)
        self.memory_max.setObjectName("memory_max")
        self.horizontalLayout_15.addWidget(self.memory_max)
        self.verticalLayout_6.addWidget(self.Memory_3)
        self.Perception_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Perception_3.setObjectName("Perception_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.Perception_3)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.perc_min = QtWidgets.QCheckBox(self.Perception_3)
        self.perc_min.setObjectName("perc_min")
        self.horizontalLayout_16.addWidget(self.perc_min)
        self.perc_av = QtWidgets.QCheckBox(self.Perception_3)
        self.perc_av.setObjectName("perc_av")
        self.horizontalLayout_16.addWidget(self.perc_av)
        self.perc_max = QtWidgets.QCheckBox(self.Perception_3)
        self.perc_max.setObjectName("perc_max")
        self.horizontalLayout_16.addWidget(self.perc_max)
        self.verticalLayout_6.addWidget(self.Perception_3)
        self.Age_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Age_3.setObjectName("Age_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.Age_3)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.age_min = QtWidgets.QCheckBox(self.Age_3)
        self.age_min.setObjectName("age_min")
        self.horizontalLayout_17.addWidget(self.age_min)
        self.age_av = QtWidgets.QCheckBox(self.Age_3)
        self.age_av.setObjectName("age_av")
        self.horizontalLayout_17.addWidget(self.age_av)
        self.age_max = QtWidgets.QCheckBox(self.Age_3)
        self.age_max.setObjectName("age_max")
        self.horizontalLayout_17.addWidget(self.age_max)
        self.verticalLayout_6.addWidget(self.Age_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.scrollArea_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(3)
        self.buttonBox.accepted.connect(Settings.hide)
        self.buttonBox.accepted.connect(Settings.update_Config)
        self.buttonBox.rejected.connect(Settings.hide)
        self.animationN.toggled['bool'].connect(self.update_rate.setDisabled)
        self.animationY.toggled['bool'].connect(self.pushButton_2.setDisabled)
        self.pushButton_2.clicked.connect(Settings.gshow)
        self.animationY.toggled['bool'].connect(self.mass_min.setDisabled)
        self.animationY.toggled['bool'].connect(self.mass_max.setDisabled)
        self.animationY.toggled['bool'].connect(self.velo_min.setDisabled)
        self.animationY.toggled['bool'].connect(self.memory_min.setDisabled)
        self.animationY.toggled['bool'].connect(self.perc_min.setDisabled)
        self.animationY.toggled['bool'].connect(self.age_min.setDisabled)
        self.animationY.toggled['bool'].connect(self.velo_max.setDisabled)
        self.animationY.toggled['bool'].connect(self.memory_max.setDisabled)
        self.animationY.toggled['bool'].connect(self.perc_max.setDisabled)
        self.animationY.toggled['bool'].connect(self.age_max.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.show_Biomes.setText(_translate("Settings", "activate Biomes"))
        self.show_Bord_Case.setText(_translate("Settings", "Bord Case"))
        self.show_Perception.setText(_translate("Settings", "Perception"))
        self.show_Memory.setText(_translate("Settings", "Memory"))
        self.show_Nature.setText(_translate("Settings", "Nature"))
        self.show_Minimap.setText(_translate("Settings", "Minimap"))
        self.show_Food_ProgressBar.setText(_translate("Settings", "Food ProgressBar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Settings", "Show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Settings", "Controler"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Settings", "Bobs"))
        self.groupBox.setTitle(_translate("Settings", "mode"))
        self.animationY.setText(_translate("Settings", "Animated"))
        self.label.setText(_translate("Settings", "Update rate"))
        self.animationN.setText(_translate("Settings", "Static"))
        self.pushButton_2.setText(_translate("Settings", "Show"))
        self.groupBox_3.setTitle(_translate("Settings", "Abscissa"))
        self.abcissa_tick.setText(_translate("Settings", "Ticks"))
        self.absyssa_days.setText(_translate("Settings", "Days"))
        self.gfood.setText(_translate("Settings", "Food"))
        self.gpop.setText(_translate("Settings", "Population"))
        self.Mass_3.setTitle(_translate("Settings", "Mass"))
        self.mass_min.setText(_translate("Settings", "Minimum"))
        self.mass_av.setText(_translate("Settings", "Average"))
        self.mass_max.setText(_translate("Settings", "Maximum"))
        self.velocity_3.setTitle(_translate("Settings", "Velocity"))
        self.velo_min.setText(_translate("Settings", "Minimum"))
        self.velo_av.setText(_translate("Settings", "Average"))
        self.velo_max.setText(_translate("Settings", "Maximum"))
        self.Memory_3.setTitle(_translate("Settings", "Memory"))
        self.memory_min.setText(_translate("Settings", "Minimum"))
        self.memory_av.setText(_translate("Settings", "Average"))
        self.memory_max.setText(_translate("Settings", "Maximum"))
        self.Perception_3.setTitle(_translate("Settings", "Perception"))
        self.perc_min.setText(_translate("Settings", "Minimum"))
        self.perc_av.setText(_translate("Settings", "Average"))
        self.perc_max.setText(_translate("Settings", "Maximum"))
        self.Age_3.setTitle(_translate("Settings", "Age"))
        self.age_min.setText(_translate("Settings", "Minimum"))
        self.age_av.setText(_translate("Settings", "Average"))
        self.age_max.setText(_translate("Settings", "Maximum"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Settings", "Figures"))
