# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(547, 447)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.show_Biomes = QtWidgets.QCheckBox(self.tab)
        self.show_Biomes.setGeometry(QtCore.QRect(240, 200, 122, 21))
        self.show_Biomes.setObjectName("show_Biomes")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 128, 158))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.show_Bord_Case = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Bord_Case.setObjectName("show_Bord_Case")
        self.verticalLayout.addWidget(self.show_Bord_Case)
        self.show_Perception = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Perception.setObjectName("show_Perception")
        self.verticalLayout.addWidget(self.show_Perception)
        self.show_Memory = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Memory.setObjectName("show_Memory")
        self.verticalLayout.addWidget(self.show_Memory)
        self.show_Nature = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Nature.setObjectName("show_Nature")
        self.verticalLayout.addWidget(self.show_Nature)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(181, 21, 133, 77))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.show_Minimap = QtWidgets.QCheckBox(self.layoutWidget1)
        self.show_Minimap.setObjectName("show_Minimap")
        self.verticalLayout_5.addWidget(self.show_Minimap)
        self.show_Food_ProgressBar = QtWidgets.QCheckBox(self.layoutWidget1)
        self.show_Food_ProgressBar.setObjectName("show_Food_ProgressBar")
        self.verticalLayout_5.addWidget(self.show_Food_ProgressBar)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 240, 80, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 33, 521, 171))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.brain_label = QtWidgets.QLabel(self.layoutWidget2)
        self.brain_label.setAlignment(QtCore.Qt.AlignCenter)
        self.brain_label.setObjectName("brain_label")
        self.verticalLayout_2.addWidget(self.brain_label)
        self.brain_consommation_layout = QtWidgets.QHBoxLayout()
        self.brain_consommation_layout.setObjectName("brain_consommation_layout")
        self.brain_coeff0 = QtWidgets.QSpinBox(self.layoutWidget2)
        self.brain_coeff0.setObjectName("brain_coeff0")
        self.brain_consommation_layout.addWidget(self.brain_coeff0)
        self.brain_function0 = QtWidgets.QComboBox(self.layoutWidget2)
        self.brain_function0.setObjectName("brain_function0")
        self.brain_function0.addItem("")
        self.brain_function0.addItem("")
        self.brain_function0.addItem("")
        self.brain_consommation_layout.addWidget(self.brain_function0)
        self.brain_coeff1 = QtWidgets.QSpinBox(self.layoutWidget2)
        self.brain_coeff1.setObjectName("brain_coeff1")
        self.brain_consommation_layout.addWidget(self.brain_coeff1)
        self.brain_function1 = QtWidgets.QComboBox(self.layoutWidget2)
        self.brain_function1.setObjectName("brain_function1")
        self.brain_function1.addItem("")
        self.brain_function1.addItem("")
        self.brain_function1.addItem("")
        self.brain_function1.addItem("")
        self.brain_consommation_layout.addWidget(self.brain_function1)
        self.brain_coeff2 = QtWidgets.QSpinBox(self.layoutWidget2)
        self.brain_coeff2.setObjectName("brain_coeff2")
        self.brain_consommation_layout.addWidget(self.brain_coeff2)
        self.brain_function2 = QtWidgets.QComboBox(self.layoutWidget2)
        self.brain_function2.setObjectName("brain_function2")
        self.brain_function2.addItem("")
        self.brain_function2.addItem("")
        self.brain_function2.addItem("")
        self.brain_consommation_layout.addWidget(self.brain_function2)
        self.brain_coeff3 = QtWidgets.QSpinBox(self.layoutWidget2)
        self.brain_coeff3.setObjectName("brain_coeff3")
        self.brain_consommation_layout.addWidget(self.brain_coeff3)
        self.verticalLayout_2.addLayout(self.brain_consommation_layout)
        self.move_label = QtWidgets.QLabel(self.layoutWidget2)
        self.move_label.setAlignment(QtCore.Qt.AlignCenter)
        self.move_label.setObjectName("move_label")
        self.verticalLayout_2.addWidget(self.move_label)
        self.move_consommation_layout = QtWidgets.QHBoxLayout()
        self.move_consommation_layout.setObjectName("move_consommation_layout")
        self.move_coeff0 = QtWidgets.QSpinBox(self.layoutWidget2)
        self.move_coeff0.setObjectName("move_coeff0")
        self.move_consommation_layout.addWidget(self.move_coeff0)
        self.move_function0 = QtWidgets.QComboBox(self.layoutWidget2)
        self.move_function0.setObjectName("move_function0")
        self.move_function0.addItem("")
        self.move_function0.addItem("")
        self.move_function0.addItem("")
        self.move_consommation_layout.addWidget(self.move_function0)
        self.move_coeff1 = QtWidgets.QSpinBox(self.layoutWidget2)
        self.move_coeff1.setObjectName("move_coeff1")
        self.move_consommation_layout.addWidget(self.move_coeff1)
        self.move_function1 = QtWidgets.QComboBox(self.layoutWidget2)
        self.move_function1.setObjectName("move_function1")
        self.move_function1.addItem("")
        self.move_function1.addItem("")
        self.move_function1.addItem("")
        self.move_function1.addItem("")
        self.move_consommation_layout.addWidget(self.move_function1)
        self.move_coeff2 = QtWidgets.QSpinBox(self.layoutWidget2)
        self.move_coeff2.setObjectName("move_coeff2")
        self.move_consommation_layout.addWidget(self.move_coeff2)
        self.move_function2 = QtWidgets.QComboBox(self.layoutWidget2)
        self.move_function2.setObjectName("move_function2")
        self.move_function2.addItem("")
        self.move_function2.addItem("")
        self.move_function2.addItem("")
        self.move_consommation_layout.addWidget(self.move_function2)
        self.move_coeff3 = QtWidgets.QSpinBox(self.layoutWidget2)
        self.move_coeff3.setObjectName("move_coeff3")
        self.move_consommation_layout.addWidget(self.move_coeff3)
        self.verticalLayout_2.addLayout(self.move_consommation_layout)
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(250, 230, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 260, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.animationY = QtWidgets.QRadioButton(self.groupBox)
        self.animationY.setObjectName("animationY")
        self.horizontalLayout_2.addWidget(self.animationY)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.update_rate = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.update_rate.setObjectName("update_rate")
        self.horizontalLayout_2.addWidget(self.update_rate)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.animationN = QtWidgets.QRadioButton(self.groupBox)
        self.animationN.setObjectName("animationN")
        self.horizontalLayout_2.addWidget(self.animationN)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 503, 284))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_2)
        self.formLayout.setObjectName("formLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.abcissa_tick = QtWidgets.QRadioButton(self.groupBox_3)
        self.abcissa_tick.setObjectName("abcissa_tick")
        self.horizontalLayout.addWidget(self.abcissa_tick)
        self.absyssa_days = QtWidgets.QRadioButton(self.groupBox_3)
        self.absyssa_days.setObjectName("absyssa_days")
        self.horizontalLayout.addWidget(self.absyssa_days)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_3)
        self.gfood = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.gfood.setObjectName("gfood")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gfood)
        self.gpop = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.gpop.setObjectName("gpop")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gpop)
        self.mass_av = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.mass_av.setObjectName("mass_av")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mass_av)
        self.velo_av = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.velo_av.setObjectName("velo_av")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.velo_av)
        self.memory_av = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.memory_av.setObjectName("memory_av")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.memory_av)
        self.perc_av = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.perc_av.setObjectName("perc_av")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.perc_av)
        self.age_av = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.age_av.setObjectName("age_av")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.age_av)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.scrollArea_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(23, 11, 381, 46))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Sandstorm = QtWidgets.QRadioButton(self.layoutWidget3)
        self.Sandstorm.setObjectName("Sandstorm")
        self.horizontalLayout_3.addWidget(self.Sandstorm)
        self.Sun = QtWidgets.QRadioButton(self.layoutWidget3)
        self.Sun.setObjectName("Sun")
        self.horizontalLayout_3.addWidget(self.Sun)
        self.Hail = QtWidgets.QRadioButton(self.layoutWidget3)
        self.Hail.setObjectName("Hail")
        self.horizontalLayout_3.addWidget(self.Hail)
        self.Rain = QtWidgets.QRadioButton(self.layoutWidget3)
        self.Rain.setObjectName("Rain")
        self.horizontalLayout_3.addWidget(self.Rain)
        self.Fogue = QtWidgets.QRadioButton(self.layoutWidget3)
        self.Fogue.setObjectName("Fogue")
        self.horizontalLayout_3.addWidget(self.Fogue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(4)
        self.buttonBox.accepted.connect(Settings.hide)
        self.buttonBox.accepted.connect(Settings.update_Config)
        self.buttonBox.rejected.connect(Settings.hide)
        self.animationN.toggled['bool'].connect(self.update_rate.setDisabled)
        self.animationY.toggled['bool'].connect(self.pushButton_2.setDisabled)
        self.pushButton_2.clicked.connect(Settings.gshow)
        self.pushButton.clicked.connect(Settings.update_consommation_label)
        self.pushButton_4.clicked.connect(Settings.restart)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.show_Biomes.setText(_translate("Settings", "activate Biomes"))
        self.show_Bord_Case.setText(_translate("Settings", "Bord Case"))
        self.show_Perception.setText(_translate("Settings", "Perception"))
        self.show_Memory.setText(_translate("Settings", "Memory"))
        self.show_Nature.setText(_translate("Settings", "Nature"))
        self.show_Minimap.setText(_translate("Settings", "Minimap"))
        self.show_Food_ProgressBar.setText(_translate("Settings", "Food ProgressBar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Settings", "Show"))
        self.pushButton_4.setText(_translate("Settings", "Restart"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Settings", "Controler"))
        self.brain_label.setText(_translate("Settings", "Brain function"))
        self.brain_function0.setItemText(0, _translate("Settings", "Exponentielle"))
        self.brain_function0.setItemText(1, _translate("Settings", "Logarithme"))
        self.brain_function0.setItemText(2, _translate("Settings", "Polynôme"))
        self.brain_function1.setItemText(0, _translate("Settings", "+"))
        self.brain_function1.setItemText(1, _translate("Settings", "-"))
        self.brain_function1.setItemText(2, _translate("Settings", "x"))
        self.brain_function1.setItemText(3, _translate("Settings", "/"))
        self.brain_function2.setItemText(0, _translate("Settings", "Exponentielle"))
        self.brain_function2.setItemText(1, _translate("Settings", "Logarithme"))
        self.brain_function2.setItemText(2, _translate("Settings", "Polynôme"))
        self.move_label.setText(_translate("Settings", "Move function"))
        self.move_function0.setItemText(0, _translate("Settings", "Exponentielle"))
        self.move_function0.setItemText(1, _translate("Settings", "Logarithme"))
        self.move_function0.setItemText(2, _translate("Settings", "Polynôme"))
        self.move_function1.setItemText(0, _translate("Settings", "+"))
        self.move_function1.setItemText(1, _translate("Settings", "-"))
        self.move_function1.setItemText(2, _translate("Settings", "x"))
        self.move_function1.setItemText(3, _translate("Settings", "/"))
        self.move_function2.setItemText(0, _translate("Settings", "Exponentielle"))
        self.move_function2.setItemText(1, _translate("Settings", "Logarithme"))
        self.move_function2.setItemText(2, _translate("Settings", "Polynôme"))
        self.pushButton.setText(_translate("Settings", "Brain Refresh"))
        self.pushButton_3.setText(_translate("Settings", "Move Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Settings", "Bobs"))
        self.groupBox.setTitle(_translate("Settings", "mode"))
        self.animationY.setText(_translate("Settings", "Animated"))
        self.label.setText(_translate("Settings", "Update rate"))
        self.animationN.setText(_translate("Settings", "Static"))
        self.pushButton_2.setText(_translate("Settings", "Show"))
        self.groupBox_3.setTitle(_translate("Settings", "Abscissa"))
        self.abcissa_tick.setText(_translate("Settings", "Ticks"))
        self.absyssa_days.setText(_translate("Settings", "Days"))
        self.gfood.setText(_translate("Settings", "Food"))
        self.gpop.setText(_translate("Settings", "Population"))
        self.mass_av.setText(_translate("Settings", "Mass"))
        self.velo_av.setText(_translate("Settings", "Velocity"))
        self.memory_av.setText(_translate("Settings", "Memory"))
        self.perc_av.setText(_translate("Settings", "Perception"))
        self.age_av.setText(_translate("Settings", "Age"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Settings", "Figures"))
        self.label_2.setText(_translate("Settings", "Meteo"))
        self.Sandstorm.setText(_translate("Settings", "Sandstorm"))
        self.Sun.setText(_translate("Settings", "Sun"))
        self.Hail.setText(_translate("Settings", "Hail"))
        self.Rain.setText(_translate("Settings", "Rain"))
        self.Fogue.setText(_translate("Settings", "Fog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Settings", "Biome/Meteo"))
