# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(533, 406)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.show_Biomes = QtWidgets.QCheckBox(self.tab)
        self.show_Biomes.setGeometry(QtCore.QRect(240, 200, 122, 21))
        self.show_Biomes.setObjectName("show_Biomes")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 128, 158))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.show_Bord_Case = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Bord_Case.setObjectName("show_Bord_Case")
        self.verticalLayout.addWidget(self.show_Bord_Case)
        self.show_Perception = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Perception.setObjectName("show_Perception")
        self.verticalLayout.addWidget(self.show_Perception)
        self.show_Memory = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Memory.setObjectName("show_Memory")
        self.verticalLayout.addWidget(self.show_Memory)
        self.show_Nature = QtWidgets.QCheckBox(self.layoutWidget)
        self.show_Nature.setObjectName("show_Nature")
        self.verticalLayout.addWidget(self.show_Nature)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(181, 21, 133, 77))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.show_Minimap = QtWidgets.QCheckBox(self.layoutWidget1)
        self.show_Minimap.setObjectName("show_Minimap")
        self.verticalLayout_5.addWidget(self.show_Minimap)
        self.show_Food_ProgressBar = QtWidgets.QCheckBox(self.layoutWidget1)
        self.show_Food_ProgressBar.setObjectName("show_Food_ProgressBar")
        self.verticalLayout_5.addWidget(self.show_Food_ProgressBar)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 152, 104))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 152, 104))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.rejected.connect(Settings.hide)
        self.buttonBox.accepted.connect(Settings.hide)
        self.buttonBox.accepted.connect(Settings.update_Config)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.show_Biomes.setText(_translate("Settings", "activate Biomes"))
        self.show_Bord_Case.setText(_translate("Settings", "Bord Case"))
        self.show_Perception.setText(_translate("Settings", "Perception"))
        self.show_Memory.setText(_translate("Settings", "Memory"))
        self.show_Nature.setText(_translate("Settings", "Nature"))
        self.show_Minimap.setText(_translate("Settings", "Minimap"))
        self.show_Food_ProgressBar.setText(_translate("Settings", "Food ProgressBar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Settings", "Show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Settings", "Controler"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Settings", "Bobs"))

